[package]
name = "packtingo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
godot = { git = "https://github.com/PgBiel/gdext", branch = "wasm-test" }

[lib]
crate-type = ["cdylib"]
